### ISSUE TITLE
What happens when I upgrade RabbitMQ?

### ISSUE THREAD

**Issue by dlresende** [rabbitmq/tgir#2]
A new RabbitMQ version comes out. Exciting! Shiny new features, bug fixes, security patches, etc. It's time to upgrade. But hang on a bit: we have tens or even hundreds of applications using RabbitMQ in production. How should we go about upgrading?

This question comes up frequently in the enterprise RabbitMQ community, as part of what we call [Day 2 Operations](https://builttoadapt.io/day-two-problems-58a56e6023a3). Every company or team decide which upgrade strategy works better for them: blue-green deployment, rolling (one node at a time) upgrades, etc. But every strategy comes with its advantages and trade-offs, which are not well understood by RabbitMQ users.

What happens to clients during a rolling upgrade? What happens to particular types of queues? What if an alarm gets triggered during an upgrade? When should I expect for downtime? When there's a risk of data loss? How clusters reform after an upgrade? How to configure RabbitMQ or its clients to be upgrade-resilient? These questions come up over and over again and I think many people would benefit from some literature or guidance around RabbitMQ upgrades.

[![Coder Dilemma #9 – The Upgrade](http://www.commitstrip.com/wp-content/uploads/2016/05/Strip-Le-dilemme-de-lupgrade-650-finalenglish-2.jpg)](http://www.commitstrip.com/en/2016/05/17/coder-dilemma-9-the-upgrade/)

**Comment by gerhard** [comment]
This is a great idea, I really like the format of your proposal, especially the comic. I would like all future topic proposals to follow this format 😉

The timing of this topic couldn't be better, since:
* [RabbitMQ 3.8.0 shipped on the 1st of October 2019](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.0)
* [RabbitMQ 3.7 release series will reach End of Life on the 31st of March 2020](https://www.rabbitmq.com/versions.html)

Thanks @dlresende !
